django_LMS/urls.py
from django.contrib import admin
from django.urls import path
from LMS.views import BookDeleteView, BooksView, CustomLoginView, RegisterView, AddBookView, BookUpdateView
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page = 'books'), name='logout'),
    path('', BooksView.as_view(), name='books' ),
    path('add-book', AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>/', BookUpdateView.as_view(), name='update-book'),
    path('delete-book/<int:pk>/', BookDeleteView.as_view(), name='delete-book'),
]

LMS/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin 
)
from django.utils import timezone  
from django.utils.translation import gettext_lazy as _  
from .admin_manager import CustomAdminManager  

# Create your models here.
class Admin(AbstractBaseUser, PermissionsMixin):
    username = None  
    email = models.EmailField(_('email_address'), unique=True, max_length = 200)  
    date_joined = models.DateTimeField(auto_now_add=True)  
    is_staff = models.BooleanField(default=False)  
    is_active = models.BooleanField(default=True) 


    USERNAME_FIELD = 'email'  
    REQUIRED_FIELDS = []


    objects = CustomAdminManager()
      
    """ def has_perm(self, perm, obj=None):  
        return True  
  
    def is_staff(self):  
        return self.staff  
  
    @property  
    def is_admin(self):  
        return self.admin  
  
    def __str__(self):  
        return self.email """

    
class Book(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    isbn = models.CharField(max_length=50, null=False, blank=False)
    authors = models.CharField(max_length=300, null=True, blank=True)
    publisher = models.CharField(max_length=300, null=True, blank=True)
    date = models.DateField(auto_now_add=True)


    class Meta:
        ordering = ['date']

LMS/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm  
from django.db.models import fields  
from django import forms  
from .models import Admin  
from django.contrib.auth import get_user_model  
  
User = get_user_model()  
  
class CustomUserCreationForm(UserCreationForm):  
  
    password1 = forms.CharField(widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)  

  
    class Meta:  
        model = Admin  
        fields = ('email', )  
      
    def clean_email(self):  
        email = self.cleaned_data.get('email')  
        qs = User.objects.filter(email=email)  
        if qs.exists():  
            raise forms.ValidationError("Email is taken")  
        return email  
  
    def clean(self):  
        '''  
        Verify both passwords match.  
        '''  
        cleaned_data = super().clean()  
        password1 = cleaned_data.get("password1")  
        password2 = cleaned_data.get("password2")  
          
        if password1 is not None and password1 != password2:  
            self.add_error("password2", "Your passwords must match")  
        return cleaned_data  
  
    def save(self, commit=True):  
        # Save the provided password in hashed format  
        user = super().save(commit=False)  
        user.set_password(self.cleaned_data["password1"])  
        if commit:  
            user.save()  
        return user          
      
  
class CustomUserChangeForm(UserChangeForm):  
    class Meta:  
        model = Admin  
        fields = ('email',)  
  
    def clean_password(self):  
        # Regardless of what the user provides, return the initial value.  
        # This is done here, rather than on the field, because the  
        # field does not have access to the initial value  
        return self.initial["password1"] 

LMS/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from .forms import CustomUserCreationForm
from LMS.models import Book
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse_lazy

# Create your views here.

# Login view was customised just a little bit and inbuilt django login form was used.
class CustomLoginView(LoginView):
    template_name = 'login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('books')

# Inbuilt Register Form was used.
class RegisterView(FormView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('books')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterView, self).form_valid(form)

class BooksView(ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'books.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ''

        if search_input:
            context['books'] = context['books'].filter(name__icontains=search_input).values()
        context['search_input'] = search_input
        return context


class AddBookView(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['name', 'isbn', 'authors','publisher']
    template_name = 'addbook.html'
    success_url = reverse_lazy('books')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddBookView, self).form_valid(form)


# View that executes in Edit Tab.
class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Book
    template_name = 'updatebook.html'
    fields = ['name', 'isbn', 'authors','publisher']
    success_url = reverse_lazy('books')

class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    context_object_name = 'book'
    template_name = 'confirm-delete.html'
    success_url = reverse_lazy('books')

    

LMS/templates/addbook.html
    {% extends 'base.html' %}

    {% block content %}
    
    <style>
        #id_name, #id_isbn, #id_authors, #id_publisher{
            width: 1000px;
            height: 40px;
            border-radius: 5px;
            background-color: black;
            color: white;
            margin-left: 20px;
        }
    </style>
    
    
    
    <form method="post">
        {% csrf_token %}
        <div style=" margin-top: 100px; background-color: black; padding: 30px; opacity: 0.8;">
            <h3 style="margin:20px ;">Title:</h3>
            <span style="margin:20px ;">{{form.name}}</span>
            <h3 style="margin:20px ;">ISBN:</h3>
            <span style="margin:20px ;">{{form.isbn}}</span>
            <h3 style="margin:20px ;">Authors:</h3>
            <span style="margin:20px ;">{{form.authors}}</span>
            <h3 style="margin:20px ;">Publisher:</h3>
            <span style="margin:20px ;">{{form.publisher}}</span>
    
            
    
            <br>
            <a href="{%url 'books'%}" class="btn btn-outline-light" style="margin-top: 50px; padding: 10px; margin-left: 20px;">Back</a>
            <input  type="submit" class="btn btn-success" value="Add" style="margin-top: 50px; padding: 10px; margin-left: 20px;">
        </div>
        
    
    
        
    
    </form>
    
    
    {% endblock %}

LMS/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        
        <title>{% block title %}  {% endblock title %}</title>

    </head>
    <body style="background-image: url('https://thumbs.dreamstime.com/b/old-book-flying-letters-magic-light-background-bookshelf-library-ancient-books-as-symbol-knowledge-history-218640948.jpg');
    height: 100vh; color: white; background-attachment: fixed;">

    <nav class="navbar fixed-top navbar-expand-lg" style="background-color:rgb(83, 22, 22); opacity:0.8; color:white;">
        <h1 style="margin-left: 10px;">L!BRARY</h1>
        {% block nav %}
        {% endblock nav %}
    </nav>
        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>
        

    </body>
</html>

LMS/templates/books.html
{% extends 'base.html' %}

{% block nav %}
<div style="margin-left:50px;">
    {% if request.user.is_authenticated %}
        <h5>Welcome, Admin: <span>{{request.user}}</span> <span style="margin-left:10px;"><a class="btn btn-outline-danger" style="color:white ;" href="{% url 'logout' %}">LogOut</a></span></h5>

        <h5><a class="btn btn-outline-light" href="{% url 'add-book' %}"> + ADD BOOK</a></h5>

        
    {% else %}
    <h5>Welcome, Student. Search for your Desired books. <span style="margin-left:30px;"></span></h5>
    <a class="btn btn-outline-danger" style="color:white ;" href="{% url 'login' %}">Only, Admin Login/Register</a>

    {% endif %}
</div>

<form class="form-inline my-2 my-lg-0" style="margin-left: 100px; display: flex; ">
    <input class="form-control mr-sm-2" type="search" placeholder="Search Books by Title" aria-label="Search" name="search-area" value="{{search_input}}"  style="width: 400px;">
    <button class="btn btn-success my-2 my-sm-0" style="margin-left:20px;"  type="submit">Search</button>
</form>
{%  endblock %}

    

{% block content %}

<div>

<div class="container" style="margin-top:80px; overflow-x: scroll;">
    



    <div style="display:flex;height: 600px;" >

        {% for book in books %}
        <div class="books" id="books" style="flex: 2 0 33% ;width:80%; height: 80% ;background-color: black; opacity: 0.8 ;padding: 20px; border-radius: 20px; margin: 10px; margin-top: 80px;"> 
            <div style="width: 100% ; height:60%">
                <div style="margin:5px;">
                    <span><i style="margin-right: 10px;" class="fa">&#xf02d;</i> Title</span> 
                    <h3 style="margin-left: 15px ;">{{book.name}}</h3>
                </div>
                <div style="margin:5px;">
                    <span><i style="margin-right: 7px;" class="fa">&#xf2c3;</i>ISBN</span> 
                    <h4 style="margin-left: 15px ;">{{book.isbn}}</h4>
                </div>
                <div style="margin:5px;">
                <span><i style="margin-right: 10px;" class="fa">&#xf040;</i>Authors</span> 
                <h4 style="margin-left: 15px ;">{{book.authors}}</h4>
               </div>
               <div style="margin:5px;">
                    <span><i style="margin-right: 10px;"  class="fa fa-paperclip" aria-hidden="true"></i>Publisher</span>  
                    <h4 style="margin-left: 15px ;">{{book.publisher}}</h4>
                </div>
                
            </div>
            
            {% if request.user.is_authenticated %}

                <div style="margin-top: 80px ;">
                    <span style="margin-left:20px;">
                        <a  class="btn btn-outline-primary" href="{% url 'update-book' book.id %}" style="width:80px;color: white; font-size: 20px;">Edit</a>
                    </span>
                    
                    <span style="margin-left:20px;">
                        <a  class="btn btn-outline-danger"  href="{% url 'delete-book' book.id %}" style="width:80px;color: white; font-size: 20px;">Delete</a>
                    </span>
                </div>
            {% endif %}
        </div>
        <div>
                
        </div>
    
    {% empty %}
    
    <h1 style="margin-top: 80px; margin-left: 100px;">No Books Found</h1>
    
    
    
    {% endfor %}
    </div>  

    

</div> 

</div>




{% endblock content %}

LMS/templates/confirm-delete.html
{% extends 'base.html' %}

{% block content %}

<style>
    #id_name, #id_isbn, #id_authors, #id_publisher{
        width: 1000px;
        height: 40px;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin-left: 20px;
    }
</style>



<form method="post">
    {% csrf_token %}
    <div style=" margin-top: 100px; background-color: black; padding: 30px; opacity: 0.8;">

        <span><i style="margin-right: 10px;" class="fa">&#xf02d;</i> Title</span> 
        <h2 style="margin:20px ;">{{book.name}}</h2>
        
        <span><i style="margin-right: 7px;" class="fa">&#xf2c3;</i>ISBN</span> 
        <h2 style="margin:20px ;">{{book.isbn}}</h2>
        
        <span><i style="margin-right: 10px;" class="fa">&#xf040;</i>Authors</span> 
        <h2 style="margin:20px ;">{{book.authors}}</h2>
        
        <span><i style="margin-right: 10px;"  class="fa fa-paperclip" aria-hidden="true"></i>Publisher</span> 
        <h2 style="margin:20px ;">{{book.publisher}}</h2>
        

        

        <br>
        <a href="{%url 'books'%}" class="btn btn-outline-light" style="margin-top: 30px; padding: 10px; margin-left: 20px;">Back</a>
        <input  type="submit" class="btn btn-danger" value="Confirm" style="margin-top: 30px; padding: 10px; margin-left: 20px;">
    </div>
    


    

</form>


{% endblock %}

LMS/templates/login.html
{% extends 'base.html' %}

{% block content %}

<style>
    #id_username, #id_password{
        width: 1000px;
        height: 40px;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin-left: 20px;
    }
</style>



<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <div style=" margin-top: 100px; background-color: black; padding: 30px; opacity: 0.8;">
        <h3 style="margin:20px ;">Hello Admin, Enter Your Email Address:</h3>
        <span>{{form.username}}</span>

        <h3 style="margin:20px ;">Enter Admin Password:</h3>
        <span>{{form.password}}</span>

        <br>
        <a href="{%url 'books'%}" class="btn btn-outline-light" style="margin-top: 50px; padding: 10px; margin-left: 20px;">Back</a>
        <input  type="submit" class="btn btn-success" value="Login" style="margin-top: 50px; padding: 10px; margin-left: 20px;">
        <a href="{% url 'register' %}" class="btn btn-primary" style="margin-top: 50px; padding: 10px; margin-left: 20px;">Register</a>
        
        <div style="color:white">
            <p>{{form.errors}}</p>
        </div>
    </div>
    


    

</form>


{% endblock %}

LMS/templates/register.html
{% extends 'base.html' %}

{% block content %}

<style>
    #id_email, #id_password1, #id_password2{
        width: 1000px;
        height: 40px;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin-left: 20px;
    }
</style>



<form method="post">
    {% csrf_token %}
    <div style=" margin-top: 100px; background-color: black; padding: 30px; opacity: 0.8;">
        <h3 style="margin:20px ;">Enter Your Email Address:</h3>
        <span>{{form.email}}</span>

        <h3 style="margin:20px ;">Enter New Password:</h3>
        <span>{{form.password1}}</span>

        <h3 style="margin:20px ;">Confirm Password:</h3>
        <span>{{form.password2}}</span>

        <br>
        <a href="{%url 'books'%}" class="btn btn-outline-light" style="margin-top: 50px; padding: 10px; margin-left: 20px;">Back</a>
        <input  type="submit" class="btn btn-success" value="Register" style="margin-top: 50px; padding: 10px; margin-left: 20px;">
        
        <div style="color:white">
            <p>{{form.errors}}</p>
        </div>

    </div>
    


    

</form>


{% endblock %}

LMS/templates/updatebook.html
{% extends 'base.html' %}

{% block content %}

<style>
    #id_name, #id_isbn, #id_authors, #id_publisher{
        width: 1000px;
        height: 40px;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin-left: 20px;
    }
</style>



<form method="post">
    {% csrf_token %}
    <div style=" margin-top: 100px; background-color: black; padding: 30px; opacity: 0.8;">
        <h3 style="margin:20px ;">Title:</h3>
        <span style="margin:20px ;">{{form.name}}</span>
        <h3 style="margin:20px ;">ISBN:</h3>
        <span style="margin:20px ;">{{form.isbn}}</span>
        <h3 style="margin:20px ;">Authors:</h3>
        <span style="margin:20px ;">{{form.authors}}</span>
        <h3 style="margin:20px ;">Publisher:</h3>
        <span style="margin:20px ;">{{form.publisher}}</span>

        

        <br>
        <a href="{%url 'books'%}" class="btn btn-outline-light" style="margin-top: 50px; padding: 10px; margin-left: 20px;">Back</a>
        <input  type="submit" class="btn btn-success" value="Confirm" style="margin-top: 50px; padding: 10px; margin-left: 20px;">
    </div>
    


    

</form>


{% endblock %}